# Site settings
title: site title
email: your-email@domain.com
description: "site description"
encoding: utf-8
baseurl: "/VS"
url: "/"

# Build settings
markdown: rdiscount
permalink: pretty
extensions: [fenced_code_blocks]